name: Publish to pub.dev

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'

      - name: Install dependencies
        run: flutter pub get

      # - name: Check Publish Warnings
      #   run: dart pub publish --dry-run

      # - name: Setup Pub Credentials
      #   run: |
      #     echo '${{ secrets.PUB_DEV_CREDENTIALS }}' > ~/.pub-cache/credentials.json

      # - name: Publish
      #   run: dart pub publish --force

      - name: Publish
        uses: k-paxian/dart-package-publisher@v1.5.1
        with:
          credentialJson: ${{ secrets.PUB_DEV_CREDENTIALS }}
          flutter: true
          skipTests: true